package com.sinura.personaltrainer.domain

/**
 * Renders the built-in catalog as a document a human can actually review.
 *
 * The catalog is now data with judgment baked into it — which equipment a lift is filed under,
 * which muscle is primary, what a secondary is worth — and every one of those calls silently
 * changes what the body map says. Reviewing that as a Kotlin file means reviewing 37 nested
 * constructor calls; reviewing it as a table grouped by lift family means seeing, in one place,
 * that the bench-press family has four members and that one of them credits the triceps as its
 * primary.
 *
 * Rendered rather than hand-maintained, and golden-file tested against the committed copy, so
 * the document cannot quietly drift away from the code it describes: change the catalog without
 * re-rendering and the build fails.
 */
object CatalogReviewRenderer {
    fun render(catalog: List<SeedExercise> = DefaultExercises.catalog()): String {
        val builder = StringBuilder()
        builder.appendLine("# Catalog v2 — review artifact")
        builder.appendLine()
        builder.appendLine(
            "Generated from `DefaultExercises.catalog()` at catalog version " +
                "${DefaultExercises.CATALOG_VERSION}. Do not edit this file by hand — it is " +
                "golden-file tested against the renderer, so a hand edit fails the build.",
        )
        builder.appendLine()
        builder.appendLine("**Invariants every row satisfies, enforced by `DefaultExercisesTest`:**")
        builder.appendLine()
        builder.appendLine("- Exactly one primary muscle, at weight 1.0.")
        builder.appendLine("- Every secondary weight is in (0, 0.5], and the secondaries of one lift sum to at most 1.0.")
        builder.appendLine("- Every `muscleKey` is exactly `CanonicalMuscle.name.lowercase()` — `quadriceps`, never `quads`.")
        builder.appendLine("- Every `movementKey` comes from the closed family vocabulary; ids are frozen and never re-slugged.")
        builder.appendLine("- `v1 muscleGroup` is unchanged from v1 and survives as display text; the `Gained` column is what v2 added.")
        builder.appendLine()
        builder.appendLine(
            "**To correct a judgment call** — an equipment type, a primary, a secondary weight " +
                "— edit the table in `docs/gameplan/PHASE_3_SCHEMA_V2.md`, apply it to " +
                "`DefaultExercises.kt`, and re-render. Corrections are cheap now and expensive " +
                "once they are on a phone.",
        )
        builder.appendLine()

        val families = catalog.groupBy { it.movementKey ?: "(none)" }
        families.keys.sorted().forEach { family ->
            val rows = families.getValue(family)
            builder.appendLine("## $family (${rows.size})")
            builder.appendLine()
            builder.appendLine("| Lift | Equipment | Load | Primary | Secondaries (weight) | v1 muscleGroup | Gained vs v1 |")
            builder.appendLine("|---|---|---|---|---|---|---|")
            rows.forEach { row ->
                val primary = row.credits.firstOrNull { it.weight == 1.0 }?.muscleKey ?: "—"
                val secondaries = row.credits
                    .filter { it.weight != 1.0 }
                    .joinToString(", ") { "${it.muscleKey} ${format(it.weight)}" }
                    .ifEmpty { "—" }
                builder.appendLine(
                    "| ${row.name} | ${row.equipment.name} | ${row.loadType.name} | $primary | " +
                        "$secondaries | ${row.muscleGroup} | ${gained(row)} |",
                )
            }
            builder.appendLine()
        }

        builder.appendLine("---")
        builder.appendLine()
        builder.appendLine("${catalog.size} lifts across ${families.size} families.")
        return builder.toString()
    }

    /**
     * What v2 added for this lift. Always the same four fields plus its credits — v1 held a name
     * and a muscle group and nothing else — but stating it per row is what makes the table
     * reviewable as a diff rather than as a fresh document.
     */
    private fun gained(row: SeedExercise): String =
        "equipment, loadType, movementKey, ${row.credits.size} credit" +
            (if (row.credits.size == 1) "" else "s")

    private fun format(weight: Double): String {
        val rounded = Math.round(weight * 100.0) / 100.0
        return if (rounded == Math.floor(rounded)) rounded.toInt().toString() else rounded.toString()
    }
}
