package com.sinura.personaltrainer.domain

/**
 * Renders every program the guided setup can generate, as a document.
 *
 * The catalog got one of these in Phase 3 and it was the only reason 98 rows of authored
 * judgment could be reviewed at all. This is the same bet on a harder problem: which lifts go
 * in a session, in what order, at what sets and reps is a training opinion, and an opinion
 * nobody can see is an opinion nobody can disagree with. There are 252 reachable combinations;
 * reading them on a phone one screen at a time is not review.
 *
 * Golden-file tested against the committed artifact, so the document and the generator cannot
 * drift apart — change the templates without re-rendering and the build fails.
 */
object PlanReviewRenderer {
    fun artifactName(): String = "onboarding-programs-review.md"

    fun render(catalog: List<Exercise> = defaultCatalog()): String {
        val out = StringBuilder()
        out.appendLine("# Guided setup — generated programs")
        out.appendLine()
        out.appendLine(
            "Every program `RoutineGenerator` can produce, rendered from the shipped catalog. " +
                "Do not edit this file by hand — it is golden-file tested against the renderer, " +
                "so a hand edit fails the build. Re-render with `tools/render-artifacts.sh`.",
        )
        out.appendLine()
        out.appendLine("**How to read it.** Each block is one set of answers. The split is *derived*, never asked.")
        out.appendLine(
            "Sets, reps and rest come from `ProgramDose` (age, goal, days) on top of " +
                "`AddDefaults` (load type and role). A hand-added lift still uses `AddDefaults` alone.",
        )
        out.appendLine("Lift order is compounds first — the lift that asks most of you should meet you fresh.")
        out.appendLine("Strength weeks drop isolation slots; muscle weeks keep them; athletic weeks bias hinge, lunge, and carry.")
        out.appendLine()
        out.appendLine("**To change a judgment call** — which families make a session, or their order — edit")
        out.appendLine("`RoutineGenerator` templates, re-render, and review the diff here.")
        out.appendLine()

        TrainingPlace.entries.forEach { place ->
            out.appendLine("## ${place.displayName}")
            out.appendLine()
            TrainingAge.entries.forEach { age ->
                (SchedulePreferences.MIN_DAYS..SchedulePreferences.MAX_DAYS).forEach { days ->
                    TrainingGoal.entries.forEach { goal ->
                        val answers = OnboardingAnswers(
                            trainingAge = age,
                            daysPerWeek = days,
                            place = place,
                            goal = goal,
                        )
                        val plan = RoutineGenerator.generate(answers, catalog)
                        // Goal only ever breaks a tie, so most rows would be identical three
                        // times over. Print a goal only where it changed the answer.
                        val previous = if (goal == TrainingGoal.entries.first()) null else {
                            RoutineGenerator.generate(
                                answers.copy(goal = TrainingGoal.entries.first()),
                                catalog,
                            )
                        }
                        if (previous != null && previous.sameProgramAs(plan)) return@forEach
                        appendPlan(out, age, days, goal, plan)
                    }
                }
            }
        }
        appendEmphasis(out, catalog)
        return out.toString()
    }

    private fun dayCount(days: Int): String = if (days == 1) "1 day" else "$days days"

    /**
     * Balanced already appears above. These two rows exist so a reviewer can see that
     * emphasis actually changes the week, without tripling the 252-program matrix.
     */
    private fun appendEmphasis(out: StringBuilder, catalog: List<Exercise>) {
        out.appendLine("## Emphasis")
        out.appendLine()
        out.appendLine(
            "Same answers (on and off, 4 days, a full gym, general), then Upper vs Lower. " +
                "Balanced is the row already printed above.",
        )
        out.appendLine()
        listOf(TrainingEmphasis.UPPER, TrainingEmphasis.LOWER).forEach { emphasis ->
            val answers = OnboardingAnswers(
                trainingAge = TrainingAge.RETURNING,
                daysPerWeek = 4,
                place = TrainingPlace.FULL_GYM,
                goal = TrainingGoal.GENERAL,
                emphasis = emphasis,
            )
            val plan = RoutineGenerator.generate(answers, catalog)
            out.appendLine(
                "### ${answers.trainingAge.displayName} · 4 days · ${answers.goal.displayName} · " +
                    "${emphasis.displayName} → ${plan.splitStyle.displayName}",
            )
            out.appendLine()
            val week = plan.days.joinToString(" ") { day ->
                val label = day.dayOfWeek.shortLabel()
                if (day.isRest) "_${label}_" else "**$label**"
            }
            val kinds = plan.days.mapNotNull { day ->
                if (day.isRest) null else plan.routineFor(day)?.focusKind?.label
            }
            out.appendLine(
                "$week — ${plan.trainingDayCount} training days (${kinds.joinToString(" / ")})",
            )
            out.appendLine()
            plan.routines.forEach { routine ->
                out.appendLine("**${routine.name}**")
                out.appendLine()
                out.appendLine("| # | Lift | Equipment | Sets × Reps | Rest |")
                out.appendLine("|---|---|---|---|---|")
                routine.lifts.forEachIndexed { index, lift ->
                    val targets = lift.targets
                    out.appendLine(
                        "| ${index + 1} | ${lift.name} | ${lift.equipment.label} | " +
                            "${targets.sets} × ${targets.reps} | ${targets.restSeconds}s |",
                    )
                }
                out.appendLine()
            }
        }
    }

    private fun appendPlan(
        out: StringBuilder,
        age: TrainingAge,
        days: Int,
        goal: TrainingGoal,
        plan: PlanBlueprint,
    ) {
        out.appendLine("### ${age.displayName} · ${dayCount(days)} · ${goal.displayName} → ${plan.splitStyle.displayName}")
        out.appendLine()
        val week = plan.days.joinToString(" ") { day ->
            val label = day.dayOfWeek.shortLabel()
            if (day.isRest) "_${label}_" else "**$label**"
        }
        out.appendLine("$week — ${plan.trainingDayCount} training ${if (plan.trainingDayCount == 1) "day" else "days"}, ${plan.liftCount} lifts across ${plan.routines.size} ${if (plan.routines.size == 1) "session" else "sessions"}")
        out.appendLine()
        plan.routines.forEach { routine ->
            out.appendLine("**${routine.name}**")
            out.appendLine()
            out.appendLine("| # | Lift | Equipment | Sets × Reps | Rest |")
            out.appendLine("|---|---|---|---|---|")
            routine.lifts.forEachIndexed { index, lift ->
                val targets = lift.targets
                out.appendLine(
                    "| ${index + 1} | ${lift.name} | ${lift.equipment.label} | " +
                        "${targets.sets} × ${targets.reps} | ${targets.restSeconds}s |",
                )
            }
            out.appendLine()
        }
    }

    private fun defaultCatalog(): List<Exercise> = DefaultExercises.catalog().map { seed ->
        Exercise(
            id = seed.id,
            name = seed.name,
            muscleGroup = seed.muscleGroup,
            notes = "",
            isCustom = false,
            equipment = seed.equipment,
            loadType = seed.loadType,
            movementKey = seed.movementKey,
            muscles = seed.credits,
        )
    }
}
