#!/usr/bin/env python3
"""Resolve every in-project import and design-token member against real declarations.

There is no Android SDK here, so the compiler never sees this code. The syntax check
catches malformed files and check-named-args.py catches a call passing a parameter that
does not exist; this catches the third thing that survives both and still fails the build
in Android Studio: a name that was never declared.

Two passes:

  imports  every `import com.sinura.personaltrainer.<pkg>.<Name>` must resolve to a
           top-level declaration in that package.
  members  every `Metrics.x`, `Radius.x`, `InstrumentType.x`, `Motion.x`, `Haptics.x`,
           `GymMetrics.x` must be a real member of that object. These are the design
           system's whole vocabulary, so a typo here is both likely and invisible.

Usage:  tools/check-internal-imports.py [source-root]
Exit code is the number of unresolved names.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kotlin_source import kotlin_files, strip_comments_and_strings  # noqa: E402

ROOT = sys.argv[1] if len(sys.argv) > 1 else "app/src/main/java"
PREFIX = "com.sinura.personaltrainer."

# Objects whose members are the design vocabulary. Restricted to a known list so a local
# variable that happens to share a name can never produce a false positive.
TOKEN_OBJECTS = ("Metrics", "Radius", "InstrumentType", "Motion", "Haptics", "GymMetrics")

# Generated by the Android build, so they exist on the real classpath and nowhere in source.
GENERATED = {"com.sinura.personaltrainer.R", "com.sinura.personaltrainer.BuildConfig"}

PACKAGE_RE = re.compile(r"^\s*package\s+([\w.]+)", re.M)
IMPORT_RE = re.compile(r"^\s*import\s+([\w.]+)(?:\s+as\s+(\w+))?\s*$", re.M)
TOP_DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s*)*"
    r"(?:public\s+|internal\s+|private\s+|expect\s+|actual\s+|open\s+|abstract\s+|sealed\s+|data\s+|value\s+|enum\s+|annotation\s+|inline\s+|suspend\s+|external\s+)*"
    r"(?:class|object|interface|fun|val|var|typealias)\s+"
    r"(?:<[^>]*>\s+)?"
    r"(?:[\w.<>?]+\.)?"          # receiver on an extension
    r"(\w+)",
    re.M,
)
OBJECT_BODY_RE = re.compile(r"\bobject\s+(\w+)\s*\{")
MEMBER_DECL_RE = re.compile(
    r"^\s*(?:@\w+(?:\([^)]*\))?\s*)*"
    r"(?:public\s+|internal\s+|private\s+|const\s+|override\s+|open\s+|inline\s+|suspend\s+|lateinit\s+)*"
    r"(?:val|var|fun|class|object|enum\s+class)\s+"
    r"(?:<[^>]*>\s+)?(\w+)",
    re.M,
)


def balanced_body(src: str, open_index: int) -> str:
    depth = 0
    for i in range(open_index, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return src[open_index + 1:i]
    return ""


def main() -> int:
    by_package: dict[str, set[str]] = {}
    object_members: dict[str, set[str]] = {}
    sources: list[tuple[str, str]] = []

    for path in kotlin_files(ROOT):
        raw = open(path, encoding="utf-8").read()
        src = strip_comments_and_strings(raw)
        sources.append((path, src))

        match = PACKAGE_RE.search(src)
        if not match:
            continue
        package = match.group(1)
        names = by_package.setdefault(package, set())
        for decl in TOP_DECL_RE.finditer(src):
            names.add(decl.group(1))
        # Enum entries are referenced as Type.ENTRY, which the member pass does not check,
        # but the enum type itself must be importable.
        for obj in OBJECT_BODY_RE.finditer(src):
            body = balanced_body(src, obj.end() - 1)
            members = object_members.setdefault(obj.group(1), set())
            for decl in MEMBER_DECL_RE.finditer(body):
                members.add(decl.group(1))

    problems: list[str] = []

    for path, src in sources:
        for imp in IMPORT_RE.finditer(src):
            fqn = imp.group(1)
            if not fqn.startswith(PREFIX) or fqn.endswith(".*") or fqn in GENERATED:
                continue
            package, _, name = fqn.rpartition(".")
            known = by_package.get(package)
            if known is None:
                problems.append(f"{path}: import {fqn} — no such package in this source root")
            elif name not in known:
                problems.append(f"{path}: import {fqn} — '{name}' is not declared in {package}")

        for obj in TOKEN_OBJECTS:
            members = object_members.get(obj)
            if not members:
                continue
            for use in re.finditer(rf"\b{obj}\.(\w+)", src):
                if use.group(1) not in members:
                    line = src.count("\n", 0, use.start()) + 1
                    problems.append(
                        f"{path}:{line}: {obj}.{use.group(1)} — not a member of {obj}"
                    )

    for problem in sorted(set(problems)):
        print(problem)
    print()
    print(f"{len(set(problems))} unresolved name(s)")
    return len(set(problems))


if __name__ == "__main__":
    sys.exit(min(main(), 255))
