#!/usr/bin/env python3
"""Resolve every in-project import and design-token member against real declarations.

There is no Android SDK here, so the compiler never sees this code. The syntax check
catches malformed files and check-named-args.py catches a call passing a parameter that
does not exist; this catches the third thing that survives both and still fails the build
in Android Studio: a name that was never declared.

Two passes:

  imports  every `import com.sinura.personaltrainer.<pkg>.<Name>` must resolve to a
           top-level declaration in that package.
  members  every `Metrics.x`, `Radius.x`, `InstrumentType.x`, `Motion.x`, `Haptics.x`,
           `GymMetrics.x` must be a real member of that object. These are the design
           system's whole vocabulary, so a typo here is both likely and invisible.

Usage:  tools/check-internal-imports.py [source-root]
Exit code is the number of unresolved names.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kotlin_source import kotlin_files, kotlin_files_in, strip_comments_and_strings  # noqa: E402

# Every root given is indexed AND scanned together. A root scanned alone reports every
# import into another source set as unresolved — app/src/androidTest alone produces 146 such
# false positives — which is why this was main-only, and why nothing checked the imports of
# the instrumented tests at all.
MAIN_ROOT = "app/src/main/java"
ROOTS = sys.argv[1:] or [
    "app/src/main/java",
    "app/src/test/java",
    "app/src/androidTest/java",
    "app/src/debug/java",
    "app/src/sharedTest/java",
]
PREFIX = "com.sinura.personaltrainer."

# Objects whose members are the design vocabulary. Restricted to a known list so a local
# variable that happens to share a name can never produce a false positive.
TOKEN_OBJECTS = ("Metrics", "Radius", "InstrumentType", "Motion", "Haptics", "GymMetrics")

# Generated by the Android build, so they exist on the real classpath and nowhere in source.
GENERATED = {"com.sinura.personaltrainer.R", "com.sinura.personaltrainer.BuildConfig"}

PACKAGE_RE = re.compile(r"^\s*package\s+([\w.]+)", re.M)
IMPORT_RE = re.compile(r"^\s*import\s+([\w.]+)(?:\s+as\s+(\w+))?\s*$", re.M)
TOP_DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s*)*"
    # `const` belongs here: a top-level `internal const val` is a perfectly importable
    # declaration, and leaving the modifier out made every import of one read as unresolved.
    r"(?:public\s+|internal\s+|private\s+|const\s+|expect\s+|actual\s+|open\s+|abstract\s+|sealed\s+|data\s+|value\s+|enum\s+|annotation\s+|inline\s+|suspend\s+|external\s+|fun\s+)*"
    r"(?:class|object|interface|fun|val|var|typealias)\s+"
    r"(?:<[^>]*>\s+)?"
    r"(?:[\w.<>?]+\.)?"          # receiver on an extension
    r"(\w+)",
    re.M,
)
OBJECT_BODY_RE = re.compile(r"\bobject\s+(\w+)\s*\{")
ENUM_BODY_RE = re.compile(r"\benum\s+class\s+(\w+)[^{]*\{")
# An enum entry is a bare capitalised name at the head of the body, optionally with a
# constructor call or a body of its own: `CHEST(`, `CHEST,`, `CHEST {`, `CHEST ;`.
ENUM_ENTRY_RE = re.compile(r"^\s*([A-Z][A-Z0-9_]*)\s*(?:\(|,|;|\{|$)", re.M)
MEMBER_DECL_RE = re.compile(
    r"^\s*(?:@\w+(?:\([^)]*\))?\s*)*"
    r"(?:public\s+|internal\s+|private\s+|const\s+|override\s+|open\s+|inline\s+|suspend\s+|lateinit\s+)*"
    r"(?:val|var|fun|class|object|enum\s+class)\s+"
    r"(?:<[^>]*>\s+)?(\w+)",
    re.M,
)


def balanced_body(src: str, open_index: int) -> str:
    depth = 0
    for i in range(open_index, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return src[open_index + 1:i]
    return ""


def main() -> int:
    by_package: dict[str, set[str]] = {}
    object_members: dict[str, set[str]] = {}
    # Fully qualified type name -> its members, for `import package.Type.MEMBER`.
    type_members: dict[str, set[str]] = {}
    sources: list[tuple[str, str]] = []

    # Pooling every root into one index is what lets an androidTest file's import of a main
    # declaration resolve. It also, on its own, lets a MAIN file import something only
    # app/src/test declares — which the compiler would reject and which the old main-only
    # scan caught. So the root each declaration came from is recorded, and a main import is
    # checked against main alone.
    main_names: dict[str, set[str]] = {}
    for path in kotlin_files_in(ROOTS):
        raw = open(path, encoding="utf-8").read()
        src = strip_comments_and_strings(raw)
        sources.append((path, src))

        match = PACKAGE_RE.search(src)
        if not match:
            continue
        package = match.group(1)
        names = by_package.setdefault(package, set())
        in_main = path.startswith(MAIN_ROOT)
        for decl in TOP_DECL_RE.finditer(src):
            names.add(decl.group(1))
            if in_main:
                main_names.setdefault(package, set()).add(decl.group(1))
        # `import a.b.SomeEnum.ENTRY` is legal Kotlin and resolves to a member of the type,
        # not to a top-level declaration, so the import pass below needs the entries indexed.
        for enum in ENUM_BODY_RE.finditer(src):
            body = balanced_body(src, enum.end() - 1)
            entries = type_members.setdefault(f"{package}.{enum.group(1)}", set())
            head = body.split(";", 1)[0]
            entries.update(ENUM_ENTRY_RE.findall(head))
            for decl in MEMBER_DECL_RE.finditer(body):
                entries.add(decl.group(1))

        for obj in OBJECT_BODY_RE.finditer(src):
            body = balanced_body(src, obj.end() - 1)
            members = object_members.setdefault(obj.group(1), set())
            for decl in MEMBER_DECL_RE.finditer(body):
                members.add(decl.group(1))

    problems: list[str] = []

    for path, src in sources:
        for imp in IMPORT_RE.finditer(src):
            fqn = imp.group(1)
            if not fqn.startswith(PREFIX) or fqn.endswith(".*") or fqn in GENERATED:
                continue
            package, _, name = fqn.rpartition(".")
            # Main code cannot see a test or debug declaration. Judging it against the pooled
            # index would let `import ...testutil.FakeClock` in a production file pass, which
            # the compiler rejects and the old main-only scan caught.
            visible = main_names if path.startswith(MAIN_ROOT) else by_package
            known = visible.get(package)
            if known is not None and name in known:
                continue
            if path.startswith(MAIN_ROOT) and by_package.get(package, set()) >= {name}:
                problems.append(
                    f"{path}: import {fqn} — '{name}' is declared only outside app/src/main, "
                    f"so production code cannot see it"
                )
                continue
            # Not a top-level name. It may be a member import — `package.Type.MEMBER` — which
            # is how enum entries and object members are pulled in. Resolve against the type.
            members = type_members.get(package)
            if members is not None:
                if name not in members:
                    problems.append(f"{path}: import {fqn} — '{name}' is not a member of {package}")
                continue
            if known is None:
                problems.append(f"{path}: import {fqn} — no such package in this source root")
            else:
                problems.append(f"{path}: import {fqn} — '{name}' is not declared in {package}")

        for obj in TOKEN_OBJECTS:
            members = object_members.get(obj)
            if not members:
                continue
            for use in re.finditer(rf"\b{obj}\.(\w+)", src):
                if use.group(1) not in members:
                    line = src.count("\n", 0, use.start()) + 1
                    problems.append(
                        f"{path}:{line}: {obj}.{use.group(1)} — not a member of {obj}"
                    )

    for problem in sorted(set(problems)):
        print(problem)
    print()
    print(f"{len(set(problems))} unresolved name(s)")
    return len(set(problems))


if __name__ == "__main__":
    sys.exit(min(main(), 255))
