package com.sinura.personaltrainer.ui.components

import androidx.annotation.DrawableRes
import com.sinura.personaltrainer.R

/**
 * One WebP still per catalog lift, keyed by [Exercise.imageKey].
 *
 * Family stills in [artworkFor] stay the fallback for customs and
 * unknown keys. Body tab unlit/heat stills are not this pack.
 */
@DrawableRes
internal fun keyedArtwork(imageKey: String?): Int? {
    if (imageKey.isNullOrBlank()) return null
    return KEYED[imageKey]
}

private val KEYED: Map<String, Int> = mapOf(
    "ex_ab_wheel_rollout" to R.drawable.ex_ab_wheel_rollout,
    "ex_arnold_press" to R.drawable.ex_arnold_press,
    "ex_assisted_chin_up" to R.drawable.ex_assisted_chin_up,
    "ex_assisted_dip" to R.drawable.ex_assisted_dip,
    "ex_assisted_pull_up" to R.drawable.ex_assisted_pull_up,
    "ex_back_extension" to R.drawable.ex_back_extension,
    "ex_barbell_back_squat" to R.drawable.ex_barbell_back_squat,
    "ex_barbell_bench_press" to R.drawable.ex_barbell_bench_press,
    "ex_barbell_curl" to R.drawable.ex_barbell_curl,
    "ex_barbell_glute_bridge" to R.drawable.ex_barbell_glute_bridge,
    "ex_barbell_row" to R.drawable.ex_barbell_row,
    "ex_barbell_shrug" to R.drawable.ex_barbell_shrug,
    "ex_bench_dip" to R.drawable.ex_bench_dip,
    "ex_bodyweight_squat" to R.drawable.ex_bodyweight_squat,
    "ex_bulgarian_split_squat" to R.drawable.ex_bulgarian_split_squat,
    "ex_cable_crunch" to R.drawable.ex_cable_crunch,
    "ex_cable_curl" to R.drawable.ex_cable_curl,
    "ex_cable_fly" to R.drawable.ex_cable_fly,
    "ex_cable_kickback" to R.drawable.ex_cable_kickback,
    "ex_cable_lateral_raise" to R.drawable.ex_cable_lateral_raise,
    "ex_cable_pull_through" to R.drawable.ex_cable_pull_through,
    "ex_chest_fly" to R.drawable.ex_chest_fly,
    "ex_chest_supported_dumbbell_row" to R.drawable.ex_chest_supported_dumbbell_row,
    "ex_chin_up" to R.drawable.ex_chin_up,
    "ex_close_grip_bench_press" to R.drawable.ex_close_grip_bench_press,
    "ex_close_grip_lat_pulldown" to R.drawable.ex_close_grip_lat_pulldown,
    "ex_conventional_deadlift" to R.drawable.ex_conventional_deadlift,
    "ex_dead_bug" to R.drawable.ex_dead_bug,
    "ex_decline_bench_press" to R.drawable.ex_decline_bench_press,
    "ex_decline_sit_up" to R.drawable.ex_decline_sit_up,
    "ex_diamond_push_up" to R.drawable.ex_diamond_push_up,
    "ex_dip" to R.drawable.ex_dip,
    "ex_dumbbell_bench_press" to R.drawable.ex_dumbbell_bench_press,
    "ex_dumbbell_curl" to R.drawable.ex_dumbbell_curl,
    "ex_dumbbell_rear_delt_fly" to R.drawable.ex_dumbbell_rear_delt_fly,
    "ex_dumbbell_romanian_deadlift" to R.drawable.ex_dumbbell_romanian_deadlift,
    "ex_dumbbell_shrug" to R.drawable.ex_dumbbell_shrug,
    "ex_dumbbell_step_up" to R.drawable.ex_dumbbell_step_up,
    "ex_ez_bar_curl" to R.drawable.ex_ez_bar_curl,
    "ex_face_pull" to R.drawable.ex_face_pull,
    "ex_farmer_s_carry" to R.drawable.ex_farmer_s_carry,
    "ex_front_squat" to R.drawable.ex_front_squat,
    "ex_goblet_squat" to R.drawable.ex_goblet_squat,
    "ex_good_morning" to R.drawable.ex_good_morning,
    "ex_hack_squat" to R.drawable.ex_hack_squat,
    "ex_hammer_curl" to R.drawable.ex_hammer_curl,
    "ex_hanging_leg_raise" to R.drawable.ex_hanging_leg_raise,
    "ex_hip_abduction_machine" to R.drawable.ex_hip_abduction_machine,
    "ex_hip_thrust" to R.drawable.ex_hip_thrust,
    "ex_hyper_pro_45_degree_back_extension" to R.drawable.ex_hyper_pro_45_degree_back_extension,
    "ex_hyper_pro_90_degree_back_extension" to R.drawable.ex_hyper_pro_90_degree_back_extension,
    "ex_hyper_pro_bicep_curl" to R.drawable.ex_hyper_pro_bicep_curl,
    "ex_hyper_pro_bulgarian_split_squat" to R.drawable.ex_hyper_pro_bulgarian_split_squat,
    "ex_hyper_pro_calf_stretch" to R.drawable.ex_hyper_pro_calf_stretch,
    "ex_hyper_pro_couch_stretch" to R.drawable.ex_hyper_pro_couch_stretch,
    "ex_hyper_pro_elephant_walk" to R.drawable.ex_hyper_pro_elephant_walk,
    "ex_hyper_pro_external_rotator" to R.drawable.ex_hyper_pro_external_rotator,
    "ex_hyper_pro_face_pull" to R.drawable.ex_hyper_pro_face_pull,
    "ex_hyper_pro_ghd_sit_up" to R.drawable.ex_hyper_pro_ghd_sit_up,
    "ex_hyper_pro_glute_ham_raise" to R.drawable.ex_hyper_pro_glute_ham_raise,
    "ex_hyper_pro_hamstring_curl" to R.drawable.ex_hyper_pro_hamstring_curl,
    "ex_hyper_pro_hip_thrust" to R.drawable.ex_hyper_pro_hip_thrust,
    "ex_hyper_pro_incline_pigeon" to R.drawable.ex_hyper_pro_incline_pigeon,
    "ex_hyper_pro_kot_squat" to R.drawable.ex_hyper_pro_kot_squat,
    "ex_hyper_pro_leg_extension" to R.drawable.ex_hyper_pro_leg_extension,
    "ex_hyper_pro_leg_raise" to R.drawable.ex_hyper_pro_leg_raise,
    "ex_hyper_pro_nordic_curl" to R.drawable.ex_hyper_pro_nordic_curl,
    "ex_hyper_pro_pullover" to R.drawable.ex_hyper_pro_pullover,
    "ex_hyper_pro_push_up" to R.drawable.ex_hyper_pro_push_up,
    "ex_hyper_pro_ql_raise" to R.drawable.ex_hyper_pro_ql_raise,
    "ex_hyper_pro_reverse_hyper" to R.drawable.ex_hyper_pro_reverse_hyper,
    "ex_hyper_pro_reverse_nordic" to R.drawable.ex_hyper_pro_reverse_nordic,
    "ex_hyper_pro_russian_twist" to R.drawable.ex_hyper_pro_russian_twist,
    "ex_hyper_pro_sit_up" to R.drawable.ex_hyper_pro_sit_up,
    "ex_hyper_pro_standing_row" to R.drawable.ex_hyper_pro_standing_row,
    "ex_hyper_pro_trap_3_raise" to R.drawable.ex_hyper_pro_trap_3_raise,
    "ex_hyper_pro_woodchop" to R.drawable.ex_hyper_pro_woodchop,
    "ex_incline_bench_press" to R.drawable.ex_incline_bench_press,
    "ex_incline_dumbbell_bench_press" to R.drawable.ex_incline_dumbbell_bench_press,
    "ex_incline_dumbbell_curl" to R.drawable.ex_incline_dumbbell_curl,
    "ex_inverted_row" to R.drawable.ex_inverted_row,
    "ex_kettlebell_swing" to R.drawable.ex_kettlebell_swing,
    "ex_lat_pulldown" to R.drawable.ex_lat_pulldown,
    "ex_lateral_raise" to R.drawable.ex_lateral_raise,
    "ex_leg_curl" to R.drawable.ex_leg_curl,
    "ex_leg_extension" to R.drawable.ex_leg_extension,
    "ex_leg_press" to R.drawable.ex_leg_press,
    "ex_leg_press_calf_raise" to R.drawable.ex_leg_press_calf_raise,
    "ex_machine_bicep_curl" to R.drawable.ex_machine_bicep_curl,
    "ex_machine_chest_press" to R.drawable.ex_machine_chest_press,
    "ex_machine_crunch" to R.drawable.ex_machine_crunch,
    "ex_machine_hip_thrust" to R.drawable.ex_machine_hip_thrust,
    "ex_machine_lateral_raise" to R.drawable.ex_machine_lateral_raise,
    "ex_machine_seated_row" to R.drawable.ex_machine_seated_row,
    "ex_machine_shoulder_press" to R.drawable.ex_machine_shoulder_press,
    "ex_machine_triceps_extension" to R.drawable.ex_machine_triceps_extension,
    "ex_nordic_ham_curl" to R.drawable.ex_nordic_ham_curl,
    "ex_one_arm_dumbbell_row" to R.drawable.ex_one_arm_dumbbell_row,
    "ex_overhead_cable_triceps_extension" to R.drawable.ex_overhead_cable_triceps_extension,
    "ex_overhead_dumbbell_triceps_extension" to R.drawable.ex_overhead_dumbbell_triceps_extension,
    "ex_overhead_press" to R.drawable.ex_overhead_press,
    "ex_pec_deck" to R.drawable.ex_pec_deck,
    "ex_pendlay_row" to R.drawable.ex_pendlay_row,
    "ex_plank" to R.drawable.ex_plank,
    "ex_preacher_curl" to R.drawable.ex_preacher_curl,
    "ex_pull_up" to R.drawable.ex_pull_up,
    "ex_push_press" to R.drawable.ex_push_press,
    "ex_push_up" to R.drawable.ex_push_up,
    "ex_reverse_lunge" to R.drawable.ex_reverse_lunge,
    "ex_reverse_pec_deck" to R.drawable.ex_reverse_pec_deck,
    "ex_romanian_deadlift" to R.drawable.ex_romanian_deadlift,
    "ex_russian_twist" to R.drawable.ex_russian_twist,
    "ex_seated_cable_row" to R.drawable.ex_seated_cable_row,
    "ex_seated_calf_raise" to R.drawable.ex_seated_calf_raise,
    "ex_seated_dumbbell_press" to R.drawable.ex_seated_dumbbell_press,
    "ex_seated_leg_curl" to R.drawable.ex_seated_leg_curl,
    "ex_side_plank" to R.drawable.ex_side_plank,
    "ex_single_leg_calf_raise" to R.drawable.ex_single_leg_calf_raise,
    "ex_single_leg_romanian_deadlift" to R.drawable.ex_single_leg_romanian_deadlift,
    "ex_skull_crusher" to R.drawable.ex_skull_crusher,
    "ex_smith_machine_bench_press" to R.drawable.ex_smith_machine_bench_press,
    "ex_smith_machine_squat" to R.drawable.ex_smith_machine_squat,
    "ex_standing_calf_raise" to R.drawable.ex_standing_calf_raise,
    "ex_straight_arm_pulldown" to R.drawable.ex_straight_arm_pulldown,
    "ex_sumo_deadlift" to R.drawable.ex_sumo_deadlift,
    "ex_t_bar_row" to R.drawable.ex_t_bar_row,
    "ex_trap_bar_deadlift" to R.drawable.ex_trap_bar_deadlift,
    "ex_tricep_pushdown" to R.drawable.ex_tricep_pushdown,
    "ex_walking_lunge" to R.drawable.ex_walking_lunge,
)

internal val KEYED_STILL_KEYS: Set<String> = KEYED.keys


